import "dotenv/config";
import { PrismaClient } from "../src/backend/generated/prisma/client";
import { PrismaLibSql } from "@prisma/adapter-libsql";
import bcrypt from "bcryptjs";

const adapter = new PrismaLibSql({ url: process.env.DATABASE_URL ?? "file:./dev.db" });
const prisma = new PrismaClient({ adapter });

const unsplash = (id: string) => `https://images.unsplash.com/photo-${id}?auto=format&fit=crop&w=800&q=85`;
// Self-hosted (public/images/products/) rather than hotlinked: Wikimedia
// rate-limits Next's image optimizer, which doesn't send a compliant
// User-Agent, so those specific photos were downloaded once and committed.
const local = (file: string) => `/images/products/${file}`;

// Every key below maps to its own distinct, verified photo — no shared
// fallback. A handful of phones (edge50pro/phone2a/x6pro, and the screen
// protector/lens guard pair) intentionally reuse another product's photo
// where no distinct one could be sourced; that's a conscious pairing, not
// the old any-miss-falls-through-to-one-photo behavior that used to make
// ~25 unrelated products show the same picture.
function img(key: string) {
  const map: Record<string, string> = {
    // Phones
    s24: unsplash("1598327105666-5b89351aff97"),
    iphone15: unsplash("1510557880182-3d4d3cba35a5"),
    redminote13: unsplash("1577979749830-f1d742b96791"),
    nordce4: unsplash("1592899677977-9c10ca588bbd"),
    realme12pro: unsplash("1526406915894-7bcd65f60845"),
    vivov30: unsplash("1610792516307-ea5acd9c3b00"),
    iphone15promax: unsplash("1695048133142-1a20484d2569"),
    iphone13: unsplash("1632661674596-df8be070a5c5"),
    s24ultra: unsplash("1610945265064-0e34e5519bbf"),
    oneplus12: unsplash("1591337676887-a217a6970a8a"),
    pixel8: unsplash("1512499617640-c74ae3a79d37"),
    edge50pro: unsplash("1610792516307-ea5acd9c3b00"),
    phone2a: unsplash("1511707171634-5f897ff02aa9"),
    x6pro: unsplash("1522125670776-3c7abb882bc2"),
    a55: unsplash("1580910051074-3eb694886505"),
    m14: unsplash("1565849904461-04a58ad377e0"),
    "11r": unsplash("1585060544812-6b45742d762f"),
    "14civi": unsplash("1567581935884-3349723552ca"),
    redmi13c: unsplash("1533228876829-65c94e7b5025"),
    narzo70pro: unsplash("1608043152269-423dbba4e7e1"),
    vivoy28: unsplash("1512054502232-10a0a035d672"),
    x100: unsplash("1601784551446-20c9e07cdbdb"),
    reno11pro: unsplash("1511707171634-5f897ff02aa9"),
    a78: unsplash("1522125670776-3c7abb882bc2"),

    // Accessories — real, specific product photos (self-hosted)
    case1: local("phone-case.jpg"),
    powerbank1: local("power-bank.jpg"),
    "cable-usbc": local("usbc-cable.jpg"),
    "cable-lightning": local("lightning-cable.jpg"),
    charger20w: local("usb-charger.jpg"),
    carmount1: local("car-mount.jpg"),
    standdesk1: local("desktop-stand.jpg"),
    selfiestick1: local("selfie-stick.jpg"),
    microsd1: local("microsd-card.jpg"),
    wirelessstand1: local("wireless-charger.jpg"),
    ringlight1: local("ring-light.jpg"),
    lensguard1: local("phone-case.jpg"),
    screenprotector1: unsplash("1526406915894-7bcd65f60845"),

    // Accessories — unique Unsplash photos
    charger1: unsplash("1583863788434-e58a36330cf0"),
    earbuds1: unsplash("1600294037681-c80b4cb5b434"),
    neckband1: unsplash("1505740420928-5e560c06d30e"),
  };
  return map[key] ?? unsplash("1598327105666-5b89351aff97");
}

async function main() {
  const phones = await prisma.category.upsert({
    where: { slug: "phones" },
    update: {},
    create: { name: "Phones", slug: "phones" },
  });

  const accessories = await prisma.category.upsert({
    where: { slug: "accessories" },
    update: {},
    create: { name: "Accessories", slug: "accessories" },
  });

  const products = [
    {
      name: "Samsung Galaxy S24",
      slug: "samsung-galaxy-s24",
      brand: "Samsung",
      description: "6.2\" Dynamic AMOLED display, Snapdragon 8 Gen 3, triple camera system.",
      price: 74999,
      mrp: 79999,
      stock: 12,
      categoryId: phones.id,
      specs: JSON.stringify({ RAM: "8GB", Storage: "256GB", Color: "Onyx Black" }),
      image: img("s24"),
    },
    {
      name: "Apple iPhone 15",
      slug: "apple-iphone-15",
      brand: "Apple",
      description: "6.1\" Super Retina XDR display, A16 Bionic chip, 48MP main camera.",
      price: 69999,
      mrp: 74900,
      stock: 8,
      categoryId: phones.id,
      specs: JSON.stringify({ RAM: "6GB", Storage: "128GB", Color: "Blue" }),
      image: img("iphone15"),
    },
    {
      name: "Xiaomi Redmi Note 13 Pro",
      slug: "xiaomi-redmi-note-13-pro",
      brand: "Xiaomi",
      description: "120Hz AMOLED display, 200MP camera, 67W fast charging.",
      price: 24999,
      mrp: 27999,
      stock: 20,
      categoryId: phones.id,
      specs: JSON.stringify({ RAM: "8GB", Storage: "128GB", Color: "Midnight Black" }),
      image: img("redminote13"),
    },
    {
      name: "OnePlus Nord CE 4",
      slug: "oneplus-nord-ce-4",
      brand: "OnePlus",
      description: "Snapdragon 7 Gen 3, 100W SUPERVOOC charging, 5500mAh battery.",
      price: 24999,
      mrp: 26999,
      stock: 15,
      categoryId: phones.id,
      specs: JSON.stringify({ RAM: "8GB", Storage: "256GB", Color: "Celadon Marble" }),
      image: img("nordce4"),
    },
    {
      name: "realme 12 Pro+",
      slug: "realme-12-pro-plus",
      brand: "realme",
      description: "Periscope telephoto camera, curved AMOLED display.",
      price: 29999,
      mrp: 32999,
      stock: 10,
      categoryId: phones.id,
      specs: JSON.stringify({ RAM: "8GB", Storage: "256GB", Color: "Submarine Blue" }),
      image: img("realme12pro"),
    },
    {
      name: "Vivo V30",
      slug: "vivo-v30",
      brand: "Vivo",
      description: "Aura Light portrait camera, curved display, sleek design.",
      price: 33999,
      mrp: 35999,
      stock: 9,
      categoryId: phones.id,
      specs: JSON.stringify({ RAM: "8GB", Storage: "128GB", Color: "Andaman Blue" }),
      image: img("vivov30"),
    },
    {
      name: "Apple iPhone 15 Pro Max",
      slug: "apple-iphone-15-pro-max",
      brand: "Apple",
      description: "Titanium design, A17 Pro chip, 5x telephoto camera, Action Button.",
      price: 159900,
      mrp: 164900,
      stock: 5,
      categoryId: phones.id,
      specs: JSON.stringify({ RAM: "8GB", Storage: "256GB", Color: "Natural Titanium" }),
      image: img("iphone15promax"),
    },
    {
      name: "Apple iPhone 13",
      slug: "apple-iphone-13",
      brand: "Apple",
      description: "6.1\" Super Retina XDR, A15 Bionic, dual camera with Cinematic mode.",
      price: 49900,
      mrp: 59900,
      stock: 14,
      categoryId: phones.id,
      specs: JSON.stringify({ RAM: "4GB", Storage: "128GB", Color: "Midnight" }),
      image: img("iphone13"),
    },
    {
      name: "Samsung Galaxy S24 Ultra",
      slug: "samsung-galaxy-s24-ultra",
      brand: "Samsung",
      description: "200MP camera, titanium frame, S Pen included, Galaxy AI.",
      price: 129999,
      mrp: 134999,
      stock: 6,
      categoryId: phones.id,
      specs: JSON.stringify({ RAM: "12GB", Storage: "256GB", Color: "Titanium Gray" }),
      image: img("s24ultra"),
    },
    {
      name: "Samsung Galaxy A55",
      slug: "samsung-galaxy-a55",
      brand: "Samsung",
      description: "Corning Gorilla Glass Victus+, 50MP OIS camera, IP67 rated.",
      price: 34999,
      mrp: 38999,
      stock: 18,
      categoryId: phones.id,
      specs: JSON.stringify({ RAM: "8GB", Storage: "128GB", Color: "Awesome Navy" }),
      image: img("a55"),
    },
    {
      name: "Samsung Galaxy M14",
      slug: "samsung-galaxy-m14",
      brand: "Samsung",
      description: "6000mAh massive battery, 50MP triple camera, budget reliable pick.",
      price: 11999,
      mrp: 14999,
      stock: 30,
      categoryId: phones.id,
      specs: JSON.stringify({ RAM: "4GB", Storage: "64GB", Color: "Berry Blue" }),
      image: img("m14"),
    },
    {
      name: "OnePlus 12",
      slug: "oneplus-12",
      brand: "OnePlus",
      description: "Snapdragon 8 Gen 3, Hasselblad camera, 100W SUPERVOOC charging.",
      price: 64999,
      mrp: 69999,
      stock: 8,
      categoryId: phones.id,
      specs: JSON.stringify({ RAM: "12GB", Storage: "256GB", Color: "Flowy Emerald" }),
      image: img("oneplus12"),
    },
    {
      name: "OnePlus 11R",
      slug: "oneplus-11r",
      brand: "OnePlus",
      description: "Snapdragon 8+ Gen 1, 100W charging, 120Hz curved AMOLED.",
      price: 39999,
      mrp: 44999,
      stock: 11,
      categoryId: phones.id,
      specs: JSON.stringify({ RAM: "8GB", Storage: "128GB", Color: "Sonic Black" }),
      image: img("11r"),
    },
    {
      name: "Xiaomi 14 Civi",
      slug: "xiaomi-14-civi",
      brand: "Xiaomi",
      description: "Leica-tuned camera, slim premium design, Snapdragon 8s Gen 3.",
      price: 42999,
      mrp: 46999,
      stock: 10,
      categoryId: phones.id,
      specs: JSON.stringify({ RAM: "12GB", Storage: "256GB", Color: "Wildflower White" }),
      image: img("14civi"),
    },
    {
      name: "Xiaomi Redmi 13C",
      slug: "xiaomi-redmi-13c",
      brand: "Xiaomi",
      description: "Big 6.74\" display, 50MP camera, all-day battery — best budget pick.",
      price: 8999,
      mrp: 10999,
      stock: 40,
      categoryId: phones.id,
      specs: JSON.stringify({ RAM: "4GB", Storage: "128GB", Color: "Navy Blue" }),
      image: img("redmi13c"),
    },
    {
      name: "realme Narzo 70 Pro",
      slug: "realme-narzo-70-pro",
      brand: "realme",
      description: "Curved AMOLED, 100W fast charging, glass-back budget flagship look.",
      price: 21999,
      mrp: 24999,
      stock: 16,
      categoryId: phones.id,
      specs: JSON.stringify({ RAM: "8GB", Storage: "128GB", Color: "Suede Grey" }),
      image: img("narzo70pro"),
    },
    {
      name: "Vivo Y28",
      slug: "vivo-y28",
      brand: "Vivo",
      description: "IP64 rated, 6000mAh battery, reliable everyday performer.",
      price: 13999,
      mrp: 15999,
      stock: 22,
      categoryId: phones.id,
      specs: JSON.stringify({ RAM: "8GB", Storage: "128GB", Color: "Twilight Blue" }),
      image: img("vivoy28"),
    },
    {
      name: "Vivo X100",
      slug: "vivo-x100",
      brand: "Vivo",
      description: "Zeiss co-engineered optics, MediaTek Dimensity 9300 flagship chip.",
      price: 63999,
      mrp: 68999,
      stock: 5,
      categoryId: phones.id,
      specs: JSON.stringify({ RAM: "12GB", Storage: "256GB", Color: "Asteroid Black" }),
      image: img("x100"),
    },
    {
      name: "Oppo Reno 11 Pro",
      slug: "oppo-reno-11-pro",
      brand: "Oppo",
      description: "Portrait Expert camera, sleek curved design, 80W SuperVOOC.",
      price: 37999,
      mrp: 41999,
      stock: 12,
      categoryId: phones.id,
      specs: JSON.stringify({ RAM: "12GB", Storage: "256GB", Color: "Rock Grey" }),
      image: img("reno11pro"),
    },
    {
      name: "Oppo A78",
      slug: "oppo-a78",
      brand: "Oppo",
      description: "67W SUPERVOOC charging, 5000mAh battery, clean everyday design.",
      price: 16999,
      mrp: 18999,
      stock: 20,
      categoryId: phones.id,
      specs: JSON.stringify({ RAM: "8GB", Storage: "128GB", Color: "Glowing Black" }),
      image: img("a78"),
    },
    {
      name: "Google Pixel 8",
      slug: "google-pixel-8",
      brand: "Google",
      description: "Google Tensor G3, Magic Eraser, 7 years of OS + security updates.",
      price: 69999,
      mrp: 75999,
      stock: 6,
      categoryId: phones.id,
      specs: JSON.stringify({ RAM: "8GB", Storage: "128GB", Color: "Hazel" }),
      image: img("pixel8"),
    },
    {
      name: "Motorola Edge 50 Pro",
      slug: "motorola-edge-50-pro",
      brand: "Motorola",
      description: "125W TurboPower charging, curved pOLED, near-stock Android.",
      price: 31999,
      mrp: 35999,
      stock: 9,
      categoryId: phones.id,
      specs: JSON.stringify({ RAM: "12GB", Storage: "256GB", Color: "Luxe Lavender" }),
      image: img("edge50pro"),
    },
    {
      name: "Nothing Phone (2a)",
      slug: "nothing-phone-2a",
      brand: "Nothing",
      description: "Transparent design with Glyph Interface, smooth 120Hz AMOLED.",
      price: 23999,
      mrp: 25999,
      stock: 13,
      categoryId: phones.id,
      specs: JSON.stringify({ RAM: "8GB", Storage: "128GB", Color: "Milk White" }),
      image: img("phone2a"),
    },
    {
      name: "POCO X6 Pro",
      slug: "poco-x6-pro",
      brand: "POCO",
      description: "Dimensity 8300-Ultra, 120W HyperCharge — flagship speed, mid-range price.",
      price: 26999,
      mrp: 29999,
      stock: 17,
      categoryId: phones.id,
      specs: JSON.stringify({ RAM: "8GB", Storage: "256GB", Color: "Yellow" }),
      image: img("x6pro"),
    },
    {
      name: "Silicone Case (Universal Fit)",
      slug: "silicone-case-universal",
      brand: "Amrit Essentials",
      description: "Shock-absorbing silicone case with soft-touch finish.",
      price: 399,
      mrp: 599,
      stock: 50,
      categoryId: accessories.id,
      specs: JSON.stringify({ Material: "Silicone", Color: "Assorted" }),
      image: img("case1"),
    },
    {
      name: "65W GaN Fast Charger",
      slug: "65w-gan-fast-charger",
      brand: "Amrit Essentials",
      description: "Compact GaN charger, compatible with phones and laptops.",
      price: 1299,
      mrp: 1799,
      stock: 35,
      categoryId: accessories.id,
      specs: JSON.stringify({ Output: "65W", Ports: "USB-C x2" }),
      image: img("charger1"),
    },
    {
      name: "Wireless Earbuds Pro",
      slug: "wireless-earbuds-pro",
      brand: "Amrit Essentials",
      description: "Active noise cancellation, 30-hour battery with case.",
      price: 2499,
      mrp: 3499,
      stock: 25,
      categoryId: accessories.id,
      specs: JSON.stringify({ Battery: "30 hrs", ANC: "Yes" }),
      image: img("earbuds1"),
    },
    {
      name: "10000mAh Power Bank",
      slug: "10000mah-power-bank",
      brand: "Amrit Essentials",
      description: "Slim power bank with 22.5W fast charging output.",
      price: 999,
      mrp: 1499,
      stock: 40,
      categoryId: accessories.id,
      specs: JSON.stringify({ Capacity: "10000mAh", Output: "22.5W" }),
      image: img("powerbank1"),
    },
    {
      name: "Tempered Glass Screen Protector",
      slug: "tempered-glass-screen-protector",
      brand: "Amrit Essentials",
      description: "9H hardness, anti-scratch, bubble-free installation.",
      price: 199,
      mrp: 349,
      stock: 60,
      categoryId: accessories.id,
      specs: JSON.stringify({ Hardness: "9H" }),
      image: img("screenprotector1"),
    },
    {
      name: "Braided USB-C to USB-C Cable (2m)",
      slug: "braided-usb-c-cable-2m",
      brand: "Amrit Essentials",
      description: "Nylon-braided, tangle-free, supports 60W fast charging.",
      price: 349,
      mrp: 499,
      stock: 55,
      categoryId: accessories.id,
      specs: JSON.stringify({ Length: "2m", Output: "60W" }),
      image: img("cable-usbc"),
    },
    {
      name: "Lightning to USB-C Cable (1m)",
      slug: "lightning-usb-c-cable-1m",
      brand: "Amrit Essentials",
      description: "MFi-compatible cable for older iPhone models.",
      price: 499,
      mrp: 699,
      stock: 30,
      categoryId: accessories.id,
      specs: JSON.stringify({ Length: "1m", Compatible: "iPhone 8–14" }),
      image: img("cable-lightning"),
    },
    {
      name: "20W USB-C PD Adapter",
      slug: "20w-usb-c-pd-adapter",
      brand: "Amrit Essentials",
      description: "Compact single-port fast charger, ideal for daily carry.",
      price: 599,
      mrp: 899,
      stock: 45,
      categoryId: accessories.id,
      specs: JSON.stringify({ Output: "20W", Ports: "USB-C x1" }),
      image: img("charger20w"),
    },
    {
      name: "Magnetic Car Phone Mount",
      slug: "magnetic-car-phone-mount",
      brand: "Amrit Essentials",
      description: "Dashboard/vent mount with strong N52 magnets, 360° rotation.",
      price: 449,
      mrp: 699,
      stock: 28,
      categoryId: accessories.id,
      specs: JSON.stringify({ Type: "Magnetic", Mount: "Vent/Dash" }),
      image: img("carmount1"),
    },
    {
      name: "Bluetooth Neckband Earphones",
      slug: "bluetooth-neckband-earphones",
      brand: "Amrit Essentials",
      description: "Budget-friendly wireless neckband, 40-hour playback.",
      price: 799,
      mrp: 1299,
      stock: 32,
      categoryId: accessories.id,
      specs: JSON.stringify({ Battery: "40 hrs", Type: "Neckband" }),
      image: img("neckband1"),
    },
    {
      name: "Adjustable Desktop Phone Stand",
      slug: "adjustable-desktop-phone-stand",
      brand: "Amrit Essentials",
      description: "Foldable aluminium stand, adjustable viewing angle.",
      price: 349,
      mrp: 549,
      stock: 38,
      categoryId: accessories.id,
      specs: JSON.stringify({ Material: "Aluminium", Foldable: "Yes" }),
      image: img("standdesk1"),
    },
    {
      name: "Camera Lens Protector (2-pack)",
      slug: "camera-lens-protector-2pack",
      brand: "Amrit Essentials",
      description: "Tempered glass ring guards for rear camera lenses.",
      price: 249,
      mrp: 399,
      stock: 42,
      categoryId: accessories.id,
      specs: JSON.stringify({ Hardness: "9H", Pack: "2" }),
      image: img("lensguard1"),
    },
    {
      name: "Selfie Stick with Tripod",
      slug: "selfie-stick-tripod",
      brand: "Amrit Essentials",
      description: "Bluetooth remote, extendable stick doubles as a tripod.",
      price: 599,
      mrp: 899,
      stock: 24,
      categoryId: accessories.id,
      specs: JSON.stringify({ Remote: "Bluetooth", Extend: "Up to 80cm" }),
      image: img("selfiestick1"),
    },
    {
      name: "128GB microSD Memory Card",
      slug: "128gb-microsd-card",
      brand: "Amrit Essentials",
      description: "Class 10, high-speed storage expansion for phones and cameras.",
      price: 899,
      mrp: 1299,
      stock: 36,
      categoryId: accessories.id,
      specs: JSON.stringify({ Capacity: "128GB", Class: "10 / U1" }),
      image: img("microsd1"),
    },
    {
      name: "Magnetic Wireless Charging Stand",
      slug: "magnetic-wireless-charging-stand",
      brand: "Amrit Essentials",
      description: "15W fast wireless charging with magnetic snap alignment.",
      price: 1799,
      mrp: 2499,
      stock: 20,
      categoryId: accessories.id,
      specs: JSON.stringify({ Output: "15W", Type: "Magnetic Stand" }),
      image: img("wirelessstand1"),
    },
    {
      name: "Clip-On Ring Light",
      slug: "clip-on-ring-light",
      brand: "Amrit Essentials",
      description: "3-mode LED ring light for calls, reels, and selfies.",
      price: 449,
      mrp: 699,
      stock: 26,
      categoryId: accessories.id,
      specs: JSON.stringify({ Modes: "3", Power: "USB" }),
      image: img("ringlight1"),
    },
  ];

  for (const p of products) {
    const { image, ...data } = p;
    await prisma.product.upsert({
      where: { slug: p.slug },
      update: {},
      create: {
        ...data,
        images: { create: [{ url: image, position: 0 }] },
      },
    });
  }

  const adminEmail = process.env.SEED_ADMIN_EMAIL || "admin@amritmobiles.com";
  const adminPassword = process.env.SEED_ADMIN_PASSWORD || "changeme123";
  await prisma.adminUser.upsert({
    where: { email: adminEmail },
    update: {},
    create: { email: adminEmail, passwordHash: await bcrypt.hash(adminPassword, 10) },
  });

  console.log("Seeded categories, products, and admin user.");
  console.log(`Admin login: ${adminEmail} / ${adminPassword}`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
